[package]
name = "llm-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
axfetchum = { version = "0.1.4", features = ["axum"] }
axum = { version = "0.8.9", features = ["ws"] }
base64 = "0.22.1"
bcrypt = "0.19.1"
bitflags = { version = "2.11.1", features = ["serde", "std"] }
futures = "0.3.32"
futures-util = "0.3.32"
jiff = "0.2.24"
openidconnect = "4.0.1"
opentelemetry = { version = "0.32.0", features = ["logs"], optional = true }
opentelemetry-appender-tracing = { version = "0.32.0", optional = true }
opentelemetry-otlp = { version = "0.32.0", optional = true }
opentelemetry_sdk = { version = "0.32.0", features = ["logs"], optional = true }
ractor = { version = "0.15.13", features = ["async-trait"] }
rand = "0.10.1"
reqwest = { version = "0.13.3", default-features = false, features = [
  "json",
  "rustls-no-provider",
  "stream"
] }
rust-embed = { version = "8.9.0", features = ["mime-guess"], optional = true }
rustls = { version = "0.23.40", default-features = false, features = [
  "ring",
  "std"
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_repr = "0.1.20"
thiserror = "2.0.18"
time = { version = "0.3.47", features = ["serde", "std"] }
toasty = { version = "0.6.1", features = ["jiff", "sqlite"] }
toasty-cli = "0.6.1"
tokio = { version = "1.52.3", features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time"
] }
tokio-stream = { version = "0.1.18", features = ["sync"] }
tower-sessions = "0.15.0"
tracing = "0.1.44"
tracing-opentelemetry = { version = "0.33.0", optional = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ts-rs = { version = "12.0.1", features = ["serde_json", "tokio", "uuid","jiff-impl"] }
uuid = { version = "1.23.1", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3.27.0"

[features]
embed-frontend = ["rust-embed"]
otel = [
  "opentelemetry",
  "opentelemetry-appender-tracing",
  "opentelemetry-otlp",
  "opentelemetry_sdk",
  "tracing-opentelemetry",
]
postgresql = ["toasty/postgresql"]
