version = 1

[[migrations]]
id = 5386334977524604560
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 4007984964550819140
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"
