// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddModelRequest = { 
/**
 * 规范模型名（如 "openai/gpt-4o"）
 */
modelName: string, 
/**
 * 提供者侧的模型 ID
 */
providerModelId: string, compatibility: string, displayName: string, maxInputTokens: number, maxOutputTokens: number, toolCalling: boolean, vision: boolean, thinking: boolean, adaptiveThinking: boolean, 
/**
 * 提供者特定输入价格
 */
inputPricePer1m: number | null, 
/**
 * 提供者特定输出价格
 */
outputPricePer1m: number | null, cacheReadPricePer1m: number | null, };
