// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single API key entry with scheduling metadata.
 */
export type ApiKeyEntry = { label: string, key: string, weight: number, };
