// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API Key 展示（隐藏敏感信息）。
 */
export type ApiKeyDisplay = { label: string; weight: number; maskedKey: string };
