// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LMModelInfo } from "./LMModelInfo";

export type CatalogModelResponse = { model_name: string, capabilities: LMModelInfo, };
