// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCompatibility } from "./ProviderCompatibility";

export type CatalogProvider = {
  providerId: string;
  displayName: string;
  baseUrl: string;
  compat: ProviderCompatibility;
};
