// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogLink } from "./CatalogLink";

export type CatalogLinkPreview = { key: string; link: CatalogLink; exists: boolean };
