// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * models.dev 目录中提供者的简要信息（用于 Admin UI 列表/卡片展示）。
 */
export type CatalogProviderSummary = { provider_id: string, display_name: string, npm: string, doc: string, model_count: number, };
