// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogSelection = { models: Array<string>, providers: Array<string>, links: Array<string>, };
