// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogLinkPreview } from "./CatalogLinkPreview";
import type { CatalogModelPreview } from "./CatalogModelPreview";
import type { CatalogProviderPreview } from "./CatalogProviderPreview";

export type CatalogPreview = {
  sourceRev: string;
  generatedAt: string;
  models: Array<CatalogModelPreview>;
  providers: Array<CatalogProviderPreview>;
  links: Array<CatalogLinkPreview>;
};
