// Auto-generated by axfetchum. Do not edit.

import type { ModelResponse } from "./ModelResponse";
import type { ProviderResponse } from "./ProviderResponse";
import type { UpdateProviderRequest } from "./UpdateProviderRequest";

export class ApiError extends Error {
  constructor(message: string, public status: number, public body?: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export interface ApiClientOptions {
  baseUrl: string;
  getToken?: () => Promise<string | null>;
  credentials?: RequestCredentials;
  fetch?: typeof fetch;
  onError?: (error: ApiError) => void;
}

type RequestOptions = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  auth?: boolean;
};

function createRequest(options: ApiClientOptions) {
  const { baseUrl, credentials = "include" } = options;
  async function request<T>(
    path: string,
    opts: RequestOptions = {},
  ): Promise<T> {
    const { method = "GET", body, query, auth } = opts;
    // Resolve fetch at call time (not at client creation) so OTel
    // instrumentation patches are picked up even when the client
    // module is imported before telemetry initializes.
    const fetchFn = options.fetch ?? globalThis.fetch;

    let url = `${baseUrl}${path}`;
    if (query) {
      const params = new URLSearchParams();
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          params.set(key, String(value));
        }
      }
      const qs = params.toString();
      if (qs) url += `?${qs}`;
    }

    const headers: Record<string, string> = { "Content-Type": "application/json" };

    if (auth && options.getToken) {
      const token = await options.getToken();
      if (token) headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetchFn(url, {
      method,
      credentials,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      let message: string;
      let errorBody: unknown;
      try {
        const json = JSON.parse(text);
        message = json.error ?? json.message ?? text;
        errorBody = json;
      } catch {
        message = text;
      }
      const error = new ApiError(message, response.status, errorBody);
      if (options.onError) options.onError(error);
      throw error;
    }

    const text = await response.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  return request;
}

export function createApiClient(options: ApiClientOptions) {
  const request = createRequest(options);

  return {
    models: {
      listAllModels: () => request<ModelResponse[]>("/api/v1/models", { auth: true }),
      listAvailableModels: () => request<ModelResponse[]>("/api/v1/models/available", { auth: true }),
    },

    providers: {
      listProviders: () => request<ProviderResponse[]>("/api/v1/providers", { auth: true }),
      updateProvider: (provider_name: string, body: UpdateProviderRequest) =>
        request<ProviderResponse>(`/api/v1/providers/${provider_name}`, { method: "PUT", auth: true, body }),
      deleteProvider: (provider_name: string) =>
        request<void>(`/api/v1/providers/${provider_name}`, { method: "DELETE", auth: true }),
    },
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
