// Auto-generated by axfetchum. Do not edit.

import type { AddModelProviderRequest } from "./AddModelProviderRequest";
import type { AddModelRequest } from "./AddModelRequest";
import type { AdminModelResponse } from "./AdminModelResponse";
import type { CreateProviderRequest } from "./CreateProviderRequest";
import type { CreateTokenRequest } from "./CreateTokenRequest";
import type { CreateTokenResponse } from "./CreateTokenResponse";
import type { ModelInput } from "./ModelInput";
import type { ModelLinkView } from "./ModelLinkView";
import type { ModelResponse } from "./ModelResponse";
import type { OpenAiModelList } from "./OpenAiModelList";
import type { ProtocolInput } from "./ProtocolInput";
import type { ProtocolView } from "./ProtocolView";
import type { ProviderModelResponse } from "./ProviderModelResponse";
import type { ProviderQuotaResponse } from "./ProviderQuotaResponse";
import type { ProviderResponse } from "./ProviderResponse";
import type { TokenListItem } from "./TokenListItem";
import type { UpdateModelProviderRequest } from "./UpdateModelProviderRequest";
import type { UpdateModelRequest } from "./UpdateModelRequest";
import type { UpdateProviderRequest } from "./UpdateProviderRequest";
import type { UpdateRoleRequest } from "./UpdateRoleRequest";
import type { UpdateTokenRequest } from "./UpdateTokenRequest";
import type { UserResponse } from "./UserResponse";

export class ApiError extends Error {
  constructor(message: string, public status: number, public body?: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export interface ApiClientOptions {
  baseUrl: string;
  getToken?: () => Promise<string | null>;
  credentials?: RequestCredentials;
  fetch?: typeof fetch;
  onError?: (error: ApiError) => void;
}

type RequestOptions = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  auth?: boolean;
};

function createRequest(options: ApiClientOptions) {
  const { baseUrl, credentials = "include" } = options;
  async function request<T>(
    path: string,
    opts: RequestOptions = {},
  ): Promise<T> {
    const { method = "GET", body, query, auth } = opts;
    // Resolve fetch at call time (not at client creation) so OTel
    // instrumentation patches are picked up even when the client
    // module is imported before telemetry initializes.
    const fetchFn = options.fetch ?? globalThis.fetch;

    let url = `${baseUrl}${path}`;
    if (query) {
      const params = new URLSearchParams();
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          params.set(key, String(value));
        }
      }
      const qs = params.toString();
      if (qs) url += `?${qs}`;
    }

    const headers: Record<string, string> = { "Content-Type": "application/json" };

    if (auth && options.getToken) {
      const token = await options.getToken();
      if (token) headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetchFn(url, {
      method,
      credentials,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      let message: string;
      let errorBody: unknown;
      try {
        const json = JSON.parse(text);
        message = json.error ?? json.message ?? text;
        errorBody = json;
      } catch {
        message = text;
      }
      const error = new ApiError(message, response.status, errorBody);
      if (options.onError) options.onError(error);
      throw error;
    }

    const text = await response.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  return request;
}

export function createApiClient(options: ApiClientOptions) {
  const request = createRequest(options);

  return {
    admin: {
      listProviders: () => request<ProviderResponse[]>("/api/v1/admin/providers", { auth: true }),
      createProvider: (body: CreateProviderRequest) =>
        request<ProviderResponse>("/api/v1/admin/providers", { method: "POST", auth: true, body }),
      getProvider: (id: string) =>
        request<ProviderResponse>(`/api/v1/admin/providers/${id}`, { auth: true }),
      updateProvider: (id: string, body: UpdateProviderRequest) =>
        request<ProviderResponse>(`/api/v1/admin/providers/${id}`, { method: "PUT", auth: true, body }),
      deleteProvider: (id: string) =>
        request<void>(`/api/v1/admin/providers/${id}`, { method: "DELETE", auth: true }),
      listProviderProtocols: (id: string) =>
        request<ProtocolView[]>(`/api/v1/admin/providers/${id}/protocols`, { auth: true }),
      replaceProviderProtocols: (id: string, body: ProtocolInput[]) =>
        request<ProtocolView[]>(`/api/v1/admin/providers/${id}/protocols`, { method: "PUT", auth: true, body }),
      getProviderQuota: (id: string) =>
        request<ProviderQuotaResponse>(`/api/v1/admin/providers/${id}/quota`, { auth: true }),
      listProviderModels: (id: string) =>
        request<ProviderModelResponse[]>(`/api/v1/admin/providers/${id}/models`, { auth: true }),
      addProviderModel: (id: string, body: AddModelRequest) =>
        request<ProviderModelResponse>(`/api/v1/admin/providers/${id}/models`, { method: "POST", auth: true, body }),
      updateProviderModel: (id: string, model_id: string, body: UpdateModelRequest) =>
        request<ProviderModelResponse>(`/api/v1/admin/providers/${id}/models/${model_id}`, { method: "PUT", auth: true, body }),
      deleteProviderModel: (id: string, model_id: string) =>
        request<void>(`/api/v1/admin/providers/${id}/models/${model_id}`, { method: "DELETE", auth: true }),
      listAdminModels: () => request<AdminModelResponse[]>("/api/v1/admin/models", { auth: true }),
      createAdminModel: (body: ModelInput) =>
        request<AdminModelResponse>("/api/v1/admin/models", { method: "POST", auth: true, body }),
      getAdminModel: (id: string) =>
        request<AdminModelResponse>(`/api/v1/admin/models/${id}`, { auth: true }),
      updateAdminModel: (id: string, body: ModelInput) =>
        request<AdminModelResponse>(`/api/v1/admin/models/${id}`, { method: "PUT", auth: true, body }),
      deleteAdminModel: (id: string) =>
        request<void>(`/api/v1/admin/models/${id}`, { method: "DELETE", auth: true }),
      listModelProviders: (id: string) =>
        request<ModelLinkView[]>(`/api/v1/admin/models/${id}/providers`, { auth: true }),
      addModelProvider: (id: string, body: AddModelProviderRequest) =>
        request<ModelLinkView>(`/api/v1/admin/models/${id}/providers`, { method: "POST", auth: true, body }),
      updateModelProvider: (id: string, link_id: string, body: UpdateModelProviderRequest) =>
        request<ModelLinkView>(`/api/v1/admin/models/${id}/providers/${link_id}`, { method: "PUT", auth: true, body }),
      deleteModelProvider: (id: string, link_id: string) =>
        request<void>(`/api/v1/admin/models/${id}/providers/${link_id}`, { method: "DELETE", auth: true }),
      listUsers: () => request<UserResponse[]>("/api/v1/admin/users", { auth: true }),
      updateUserRole: (id: string, body: UpdateRoleRequest) =>
        request<UserResponse>(`/api/v1/admin/users/${id}/role`, { method: "PATCH", auth: true, body }),
    },

    auth: {
      login: () => `${options.baseUrl}/auth/login`,
      callback: () => `${options.baseUrl}/auth/callback`,
      me: () => request<void>("/auth/me"),
      logout: () => request<void>("/auth/logout", { method: "POST" }),
    },

    models: {
      listAllModels: () => request<ModelResponse[]>("/api/v1/models", { auth: true }),
      listAvailableModels: () => request<ModelResponse[]>("/api/v1/models/available", { auth: true }),
    },

    openai: {
      listModels: () => request<OpenAiModelList>("/v1/models", { auth: true }),
      chatCompletions: () => request<void>("/v1/chat/completions", { method: "POST" }),
    },

    tokens: {
      listTokens: () => request<TokenListItem[]>("/api/v1/tokens", { auth: true }),
      createToken: (body: CreateTokenRequest) =>
        request<CreateTokenResponse>("/api/v1/tokens", { method: "POST", auth: true, body }),
      updateToken: (id: string, body: UpdateTokenRequest) =>
        request<TokenListItem>(`/api/v1/tokens/${id}`, { method: "PATCH", auth: true, body }),
      deleteToken: (id: string) =>
        request<void>(`/api/v1/tokens/${id}`, { method: "DELETE", auth: true }),
    },
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
