// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CliSessionApproved } from "./CliSessionApproved";
import type { CliSessionPoll } from "./CliSessionPoll";

export type CliPollResponse = CliSessionApproved | CliSessionPoll;
