// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 轮询响应：approved（带一次性明文 Token）。
 */
export type CliSessionApproved = { status: string, 
/**
 * 明文 Token（仅此一次，响应后即转 consumed）。
 */
token: string, 
/**
 * Token 前缀（UI / 审计识别）。
 */
tokenPrefix: string, };
