// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 轮询响应：pending / consumed / expired（无 Token）。
 */
export type CliSessionPoll = { status: string, };
