// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-compatibility settings: path suffix, custom HTTP headers, custom HTTP params.
 */
export type CompatibilitySettings = { pathSuffix: string | null, customHeaders: { [key in string]: string }, customParams: { [key in string]: string }, };
