// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompatibilitySettings = { pathSuffix: string | null, customHeaders: Record<string, string>, customParams: Record<string, string>, };
