// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 创建 Token 的请求体（来自 API）。
 */
export type CreateTokenRequest = {
  name: string;
  allowedModels: Array<string>;
  requestQuota: number;
  tokenQuota: number;
  quotaPeriod: string;
};
