// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyEntry } from "./ApiKeyEntry";
import type { ProtocolInput } from "./ProtocolInput";

export type CreateProviderRequest = { providerId: string, displayName: string, apiKeys: Array<ApiKeyEntry>, 
/**
 * 协议列表。传入则同步替换该提供者的所有协议（语义与 PUT /protocols/ 一致）；不传或为空 [] 表示该提供者暂时不带任何协议。
 */
protocols: Array<ProtocolInput>, enabled: boolean, priority: number, };
