// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

export type CreateProviderRequest = { providerName: string, providerType: ProviderType, baseUrl: string | null, keyringService: string, keyringAccount: string, };
