// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelConnectionItem } from "./ModelConnectionItem";

export type CreateModelConnectionsRequest = { items: Array<ModelConnectionItem> };
