// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelLinkView } from "./ModelLinkView";

export type CreatedModelConnection = {
  modelId: number;
  link: ModelLinkView;
  modelCreated: boolean;
  linkCreated: boolean;
};
