// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 创建 Token 的响应体（包含明文 Token，仅返回一次）。
 */
export type CreateTokenResponse = { id: number, name: string, 
/**
 * 明文 Token（仅创建时返回一次）
 */
token: string, 
/**
 * Token 前缀（UI 识别用）
 */
token_prefix: string, allowed_models: Array<string>, request_quota: number, token_quota: number, quota_period: string, created_at: number, };
