// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 按金额/额度的模型。
 */
export type CreditQuota = {
  /**
   * 剩余额度数值。
   */
  amount: number;
  /**
   * 单位（如 `"USD"`、`"credits"`、`"CNY"`）。
   */
  currency: string;
  /**
   * 适配器特定字段。
   */
  extra?: Record<string, any>;
};
