// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 编辑工具名称集合，序列化为字符串数组
 */
export type EndpointEditToolName = { find_replace: boolean, multi_find_replace: boolean, apply_patch: boolean, code_rewrite: boolean, };
