// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyEntry } from "./ApiKeyEntry";

export type ImportModelsDevRequest = { providerId: string, 
/**
 * 可选：导入时设置 API Key（label + key）
 */
apiKeys: Array<ApiKeyEntry>, };
