// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedModel } from "./ImportedModel";

/**
 * 导入结果。
 */
export type ImportedProvider = { provider_id: string, provider_row_id: number, imported_models: Array<ImportedModel>, };
