// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaInfo } from "./QuotaInfo";

/**
 * 单个 API Key 的额度查询结果 — 供 Admin API 响应组装使用。
 */
export type KeyQuota = { 
/**
 * API Key 的 label（来自 `Provider.api_keys[*].label`）。
 */
label: string, 
/**
 * 掩码后的 API Key（仅展示用）。
 */
maskedKey: string, 
/**
 * 查询成功时的额度信息；失败时为 `None`。
 */
quota: QuotaInfo | null, 
/**
 * 错误信息（查询失败时）。
 */
error: string | null, 
/**
 * 查询时间戳（Unix 秒）。
 */
fetchedAt: number, };
