// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 消息角色，对应 LanguageModelChatMessageRole 枚举（User = 1, Assistant = 2）
 */
export type LanguageModelChatMessageRole = "User" | "Assistant";
