// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LanguageModelThinkingValue } from "./LanguageModelThinkingValue";
import { type JsonValue } from "./serde_json/JsonValue";

/**
 * 思考/推理内容部分，对应 LanguageModelThinkingPart
 */
export type LanguageModelThinkingPart = {
  value: LanguageModelThinkingValue;
  id?: string;
  metadata?: JsonValue;
};
