// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 消息角色，对应 LanguageModelChatMessageRole 枚举。
 * JSON 序列化为小写字符串（`"user"` / `"assistant"` / `"system"` / `"developer"`），
 * 与 OpenAI 协议及 ts-rs 生成的字符串字面量联合类型一致，前端无需数字→字符串映射。
 */
export type LanguageModelChatMessageRole = "user" | "assistant" | "system" | "developer";
