// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Thinking 内容的值类型，可以是单个字符串或字符串数组
 */
export type LanguageModelThinkingValue = string | Array<string>;
