// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LanguageModelToolResultContent } from "./LanguageModelToolResultContent";

/**
 * 工具结果部分，对应 LanguageModelToolResultPart
 */
export type LanguageModelToolResultPart = {
  callId: string;
  content: Array<LanguageModelToolResultContent>;
};
