// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 纯文本消息部分，对应 LanguageModelTextPart
 */
export type LanguageModelTextPart = { value: string };
