// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 二进制数据消息部分，对应 LanguageModelDataPart
 * `data` 对应 Uint8Array，序列化为数字数组
 */
export type LanguageModelDataPart = { mimeType: string; data: Array<number> };
