// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type JsonValue } from "./serde_json/JsonValue";

/**
 * Prompt TSX 消息部分，对应 LanguageModelPromptTsxPart
 */
export type LanguageModelPromptTsxPart = { value: JsonValue };
