// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type JsonValue } from "./serde_json/JsonValue";

/**
 * 工具调用部分，对应 LanguageModelToolCallPart
 */
export type LanguageModelToolCallPart = {
  callId: string;
  name: string;
  /**
   * 工具调用输入，对应 TypeScript 的 `object`
   */
  input: JsonValue;
};
