// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LanguageModelDataPart } from "./LanguageModelDataPart";
import { type LanguageModelTextPart } from "./LanguageModelTextPart";
import { type LanguageModelThinkingPart } from "./LanguageModelThinkingPart";
import { type LanguageModelToolCallPart } from "./LanguageModelToolCallPart";
import { type LanguageModelToolResultPart } from "./LanguageModelToolResultPart";

/**
 * 消息输入部分的联合类型，对应 LanguageModelInputPart:
 * LanguageModelTextPart | LanguageModelToolResultPart | LanguageModelToolCallPart | LanguageModelDataPart | LanguageModelThinkingPart
 */
export type LanguageModelInputPart =
  | LanguageModelTextPart
  | LanguageModelToolResultPart
  | LanguageModelToolCallPart
  | LanguageModelDataPart
  | LanguageModelThinkingPart;
