// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 协议无关的推理配置：effort（OpenAI）与 max_tokens（Anthropic budget_tokens）至少其一非空。
 */
export type LanguageModelReasoningConfig = { effort?: string; maxTokens?: number };
