// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LanguageModelDataPart } from "./LanguageModelDataPart";
import { type LanguageModelPromptTsxPart } from "./LanguageModelPromptTsxPart";
import { type LanguageModelTextPart } from "./LanguageModelTextPart";
import { type JsonValue } from "./serde_json/JsonValue";

/**
 * 工具结果内容的各种可能类型
 */
export type LanguageModelToolResultContent =
  | LanguageModelTextPart
  | LanguageModelPromptTsxPart
  | LanguageModelDataPart
  | JsonValue;
