// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LanguageModelChatMessageRole } from "./LanguageModelChatMessageRole";
import { type LanguageModelInputPart } from "./LanguageModelInputPart";

/**
 * 聊天消息，对应 LanguageModelChatMessage
 */
export type LanguageModelChatMessage = {
  role: LanguageModelChatMessageRole;
  content: Array<LanguageModelInputPart>;
  name: string | null;
};
