// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LanguageModelDataPart } from "./LanguageModelDataPart";
import { type LanguageModelTextPart } from "./LanguageModelTextPart";
import { type LanguageModelThinkingPart } from "./LanguageModelThinkingPart";
import { type LanguageModelToolCallPart } from "./LanguageModelToolCallPart";
import { type LanguageModelToolResultPart } from "./LanguageModelToolResultPart";
import { type LanguageModelUsagePart } from "./LanguageModelUsagePart";

/**
 * 语言模型响应部分的联合类型，对应 LMResponsePart:
 * LanguageModelTextPart | LanguageModelToolCallPart | LanguageModelDataPart | LanguageModelThinkingPart | LanguageModelToolResultPart | LanguageModelUsagePart
 */
export type LMResponsePart =
  | LanguageModelTextPart
  | LanguageModelToolCallPart
  | LanguageModelDataPart
  | LanguageModelThinkingPart
  | LanguageModelToolResultPart
  | LanguageModelUsagePart;
