// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `/auth/me` 响应 — 统一对外角色 DTO（TS 绑定 camelCase：userId/name/role/email/avatarUrl）。
 */
export type MeResponse = {
  userId: number;
  name: string;
  /**
   * `"admin"` 或 `"member"`
   */
  role: string;
  email: string | null;
  avatarUrl: string | null;
};
