// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderSummary } from "./ModelProviderSummary";

export type ModelResponse = { modelName: string, displayName: string, description: string | null, 
/**
 * 标称能力
 */
maxInputTokens: number, maxOutputTokens: number, toolCalling: boolean, vision: boolean, thinking: boolean | null, adaptiveThinking: boolean | null, 
/**
 * 提供者列表（含各自的定价和能力覆盖）
 */
providers: Array<ModelProviderSummary>, };
