// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderSummary } from "./ModelProviderSummary";

export type ModelResponse = { model_name: string, display_name: string, description: string | null, 
/**
 * 标称能力
 */
max_input_tokens: number, max_output_tokens: number, tool_calling: boolean, vision: boolean, thinking: boolean | null, adaptive_thinking: boolean | null, 
/**
 * 提供者列表（含各自的定价和能力覆盖）
 */
providers: Array<ModelProviderSummary>, };
