// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCompatibility } from "./ProviderCompatibility";

/**
 * ModelProvider 从模型视角的关联视图（带 provider 与 protocol 信息）。
 */
export type ModelLinkView = { id: number, 
/**
 * 关联的提供者 row id
 */
providerId: number, 
/**
 * 提供者显示名（JOIN 获取）
 */
providerDisplayName: string, 
/**
 * 提供者侧的模型 ID
 */
providerModelId: string, 
/**
 * 关联的协议配置
 */
protocolId: number, 
/**
 * 协议枚举
 */
protocol: ProviderCompatibility, 
/**
 * 协议端点 URL（JOIN 获取）
 */
baseUrl: string, displayName: string, maxInputTokens: number | null, maxOutputTokens: number | null, toolCalling: boolean | null, vision: boolean | null, thinking: boolean | null, adaptiveThinking: boolean | null, inputPricePer1m: number | null, outputPricePer1m: number | null, cacheReadPricePer1m: number | null, enabled: boolean, priority: number, };
