// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelRanking = {
  model: string;
  requests: number;
  totalTokens: number;
  costUsd: number;
};
