// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderSummary = { providerId: string, providerDisplayName: string, providerModelId: string, compatibility: string, maxInputTokens: number | null, maxOutputTokens: number | null, toolCalling: boolean | null, vision: boolean | null, thinking: boolean | null, adaptiveThinking: boolean | null, inputPricePer1m: number | null, outputPricePer1m: number | null, cacheReadPricePer1m: number | null, enabled: boolean, priority: number, };
