// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelResponse = { model_name: string, description: string | null, max_input_tokens: number, max_output_tokens: number, tool_calling: boolean, vision: boolean, thinking: boolean | null, adaptive_thinking: boolean | null, input_price_per_1m: number | null, output_price_per_1m: number | null, cache_read_price_per_1m: number | null, provider_ids: Array<string>, };
