// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddModelProviderRequest } from "./AddModelProviderRequest";
import type { ModelConnectionReference } from "./ModelConnectionReference";

export type ModelConnectionItem = {
  model: ModelConnectionReference;
  link: AddModelProviderRequest;
};
