// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenAiModelEntry = { id: string, object: string, created: number, owned_by: string, };
