// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenAiModelCapabilities = { max_input_tokens: number, max_output_tokens: number, tool_calling: boolean, vision: boolean, thinking: boolean | null, adaptive_thinking: boolean | null, };
