// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type OpenAiModelEntry } from "./OpenAiModelEntry";

export type OpenAiModelList = { object: string; data: Array<OpenAiModelEntry> };
