// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenAiModelProviderInfo = { provider_id: string, provider_display_name: string, 
/**
 * 提供者覆盖的能力（nullable = 使用模型标称值）
 */
max_input_tokens: number | null, max_output_tokens: number | null, tool_calling: boolean | null, vision: boolean | null, thinking: boolean | null, adaptive_thinking: boolean | null, 
/**
 * 提供者特定定价（每 1M tokens，美元）
 */
input_price_per_1m: number | null, output_price_per_1m: number | null, cache_read_price_per_1m: number | null, enabled: boolean, priority: number, };
