// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenAiModelProviderInfo = {
  providerId: string;
  providerDisplayName: string;
  /**
   * 提供者覆盖的能力（nullable = 使用模型标称值）
   */
  maxInputTokens: number | null;
  maxOutputTokens: number | null;
  toolCalling: boolean | null;
  vision: boolean | null;
  thinking: boolean | null;
  adaptiveThinking: boolean | null;
  /**
   * 提供者特定定价（每 1M tokens，美元）
   */
  inputPricePer1m: number | null;
  outputPricePer1m: number | null;
  cacheReadPricePer1m: number | null;
  enabled: boolean;
  priority: number;
};
