// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCompatConfig } from "./ProviderCompatConfig";
import type { ProviderCompatibility } from "./ProviderCompatibility";

export type ProviderResponse = { provider_name: string, compatibilities: Record<ProviderCompatibility, ProviderCompatConfig>, base_url: string | null, };
