// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderModelResponse = { id: number, provider_row_id: number, model_name: string, provider_model_id: string, compatibility: string, display_name: string, description: string | null, max_input_tokens: number, max_output_tokens: number, tool_calling: boolean, vision: boolean, thinking: boolean, adaptive_thinking: boolean, input_price_per_1m: number | null, output_price_per_1m: number | null, cache_read_price_per_1m: number | null, status: string | null, enabled: boolean, };
