// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 供应商额度适配器类型 — 声明该 Provider 使用哪种上游额度查询协议。
 *
 * `None`（数据库中为 NULL）表示该 Provider 不查询上游额度。
 * 不同适配器对应不同供应商的额度 API；新增供应商只需在此枚举中追加变体并实现
 * [`crate::quota::adapters::QuotaAdapter`]。
 */
export type ProviderQuotaAdapter = "umans";
