// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

export type ProviderResponse = { provider_name: string, provider_type: ProviderType, base_url: string | null, keyring_service: string, keyring_account: string, };
