// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type KeyQuota } from "./KeyQuota";
import { type ProviderQuotaAdapter } from "./ProviderQuotaAdapter";

/**
 * Provider 实时额度响应（`GET /api/v1/admin/providers/{id}/quota`）。
 */
export type ProviderQuotaResponse = {
  /**
   * Provider 的 row id。
   */
  id: number;
  /**
   * Provider 唯一标识（如 `"umans"`）。
   */
  providerId: string;
  /**
   * 使用的适配器类型。
   */
  adapter: ProviderQuotaAdapter;
  /**
   * 每个 API Key 的额度查询结果（顺序与 `Provider.api_keys` 一致，过滤后仅保留匹配项）。
   */
  keys: Array<KeyQuota>;
};
