// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderModelResponse = { model_name: string, provider_name: string, provider_model_name: string, priority: number, };
