// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderModelResponse = { id: number, model_id: number, provider_id: number, 
/**
 * 关联的规范模型名（需要 JOIN 获取）
 */
model_name: string, provider_model_id: string, compatibility: string, display_name: string, max_input_tokens: number | null, max_output_tokens: number | null, tool_calling: boolean | null, vision: boolean | null, thinking: boolean | null, adaptive_thinking: boolean | null, input_price_per_1m: number | null, output_price_per_1m: number | null, cache_read_price_per_1m: number | null, enabled: boolean, priority: number, };
