// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API compatibility protocol that a provider supports.
 */
export type ProviderCompatibility = "openAiChatCompletions" | "openAiResponses" | "anthropicMessages";
