// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderCompatibility = "open_ai_chat_completions" | "open_ai_responses" | "anthropic_messages";
