// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatibilitySettings } from "./CompatibilitySettings";

/**
 * Configuration for a single compatibility slot on a provider.
 */
export type ProviderCompatConfig = { enabled: boolean, settings: CompatibilitySettings | null, };
