// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 配额窗口类型 — 覆盖主流供应商的重置周期。
 */
export type QuotaWindow =
  | { slidingSeconds: number }
  | { slidingMinutes: number }
  | "calendarDaily"
  | "calendarWeekly"
  | "calendarMonthly"
  | "unknown";
