// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 适配器配置（JSON 对象字符串存储于 `Provider.quota_adapter_config`）。
 *
 * 字段全部可选，未提供时使用适配器的内置默认值。
 */
export type QuotaAdapterConfig = {
  /**
   * 覆盖适配器默认 endpoint URL（如自部署的 umans 兼容服务）。
   */
  baseUrl?: string | null;
  /**
   * 仅查询 label 匹配此值的 API Key（None = 查询全部 Key）。
   */
  keyLabelFilter?: string | null;
};
