// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditQuota } from "./CreditQuota";
import type { RequestQuota } from "./RequestQuota";

/**
 * 归一化的额度信息。
 */
export type QuotaInfo = { "kind": "requests", "data": RequestQuota } | { "kind": "credits", "data": CreditQuota };
