// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type QuotaWindow } from "./QuotaWindow";

/**
 * 按请求次数的额度模型。
 */
export type RequestQuota = {
  /**
   * 配额窗口类型（5 小时滑动、日、周、月等）。
   */
  window: QuotaWindow;
  /**
   * 限额（软上限，即正常额度）。
   */
  limit: number;
  /**
   * 当前窗口已使用请求数。
   */
  used: number;
  /**
   * 剩余请求数（`limit - used`，但部分供应商会单独返回）。
   */
  remaining: number;
  /**
   * 硬上限（部分供应商支持 burst）。
   */
  hardCap: number | null;
  /**
   * 并发会话上限（若供应商支持）。
   */
  concurrencyLimit: number | null;
  /**
   * 当前并发会话数。
   */
  concurrentSessions: number | null;
  /**
   * 适配器特定字段（如 umans 的 `tokens_in`、`tokens_out`、`plan`、`priority`）。
   */
  extra?: Record<string, any>;
};
