// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummaryQuery = {
  /**
   * 聚合最近 N 天（含今天），默认 14，上限 90。
   */
  days: number | null;
};
