// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type ProviderCompatibility } from "./ProviderCompatibility";

export type TestModelProviderResponse = {
  success: boolean;
  latencyMs: number;
  modelId: number;
  linkId: number;
  providerId: number;
  providerDisplayName: string;
  providerModelId: string;
  protocol: ProviderCompatibility;
  error: string | null;
};
