// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestModelProviderRequest = {
  /**
   * 可选自定义测试提示词。为空时使用服务端默认提示词。
   */
  prompt: string | null;
};
