// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token 列表项（不含 token_hash）。
 */
export type TokenListItem = { id: number, name: string, token_prefix: string, allowed_models: Array<string>, request_quota: number, token_quota: number, quota_period: string, active: boolean, created_at: number, last_used_at: number | null, };
