// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token 列表项（不含 token_hash）。
 */
export type TokenListItem = {
  id: number;
  name: string;
  tokenPrefix: string;
  allowedModels: Array<string>;
  requestQuota: number;
  tokenQuota: number;
  quotaPeriod: string;
  active: boolean;
  createdAt: number;
  lastUsedAt: number | null;
};
