// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageScope } from "./UsageScope";

export type TracesQuery = {
  scope?: UsageScope;
  status: string | null;
  model: string | null;
  tokenId: number | null;
  interface: string | null;
  /**
   * 模糊匹配 request_id 前缀 / error_message
   */
  search: string | null;
  /**
   * 创建时间范围（unix 秒，含边界），可选
   */
  dateFrom: number | null;
  dateTo: number | null;
  /**
   * 页码（0 起），默认 0
   */
  page: number | null;
  /**
   * 每页条数，默认 50，上限 200
   */
  pageSize: number | null;
};
