import { type LanguageModelChatMessage } from "./LanguageModelChatMessage";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type LMResponsePart } from "./LMResponsePart";

export type TraceDetail = {
  traceId: string | null;
  userId: number;
  tokenId: number;
  providerId: string;
  providerModelId: string;
  protocol: string;
  upstreamStatus: number | null;
  upstreamRequestId: string | null;
  estimatedTokens: number;
  reasoningTokens: number | null;
  firstChunkAt: number | null;
  completedAt: number | null;
  /**
   * Opt-In 内容快照
   */
  requestMessages: Array<LanguageModelChatMessage> | null;
  responseParts: Array<LMResponsePart> | null;
  requestId: string;
  interface: string;
  tokenPrefix: string;
  model: string;
  status: string;
  errorType: string | null;
  errorMessage: string | null;
  finishReason: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  cachedTokens: number | null;
  totalTokens: number | null;
  costUsd: number | null;
  ttftMs: number | null;
  latencyMs: number | null;
  /**
   * unix 秒
   */
  createdAt: number;
  /**
   * 是否有内容快照（列表页打标记用）
   */
  hasSnapshot: boolean;
};
