// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 列表页条目（不含内容快照大字段）
 */
export type TraceSummary = {
  requestId: string;
  interface: string;
  tokenPrefix: string;
  model: string;
  status: string;
  errorType: string | null;
  errorMessage: string | null;
  finishReason: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  cachedTokens: number | null;
  totalTokens: number | null;
  costUsd: number | null;
  ttftMs: number | null;
  latencyMs: number | null;
  /**
   * unix 秒
   */
  createdAt: number;
  /**
   * 是否有内容快照（列表页打标记用）
   */
  hasSnapshot: boolean;
};
