// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TracesQuery = {
  status: string | null;
  model: string | null;
  tokenId: number | null;
  interface: string | null;
  /**
   * 模糊匹配 request_id 前缀 / error_message
   */
  search: string | null;
  /**
   * 页码（0 起），默认 0
   */
  page: number | null;
  /**
   * 每页条数，默认 50，上限 200
   */
  pageSize: number | null;
};
