// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type TraceSummary } from "./TraceSummary";

export type TraceListResponse = {
  items: Array<TraceSummary>;
  total: number;
  page: number;
  pageSize: number;
};
