// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyEntry } from "./ApiKeyEntry";
import type { ProtocolInput } from "./ProtocolInput";

export type UpdateProviderRequest = { displayName: string, apiKeys: Array<ApiKeyEntry>, 
/**
 * 同 CreateProviderRequest.protocols语义：传入则同步替换；为空 [] 表示清空所有协议。
 */
protocols: Array<ProtocolInput>, enabled: boolean, priority: number, };
