// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyEntry } from "./ApiKeyEntry";
import type { CompatibilitySettings } from "./CompatibilitySettings";

export type UpdateProviderRequest = { enabled: boolean, priority: number, baseUrlOverride: string | null, apiKeys: Array<ApiKeyEntry>, compatSettings: CompatibilitySettings | null, };
