// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新 Token 的请求体。
 */
export type UpdateTokenRequest = { name: string | null, allowed_models: Array<string> | null, request_quota: number | null, token_quota: number | null, quota_period: string | null, active: boolean | null, };
