// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 从模型视角更新 provider 连接的请求体（不含 model_id，URL 提供）。
 */
export type UpdateModelProviderRequest = { providerId: number, providerModelId: string, protocolId: number, displayName: string, 
/**
 * 提供者侧覆盖值；None = 使用模型标称值（清除已有覆盖）
 */
maxInputTokens: number | null, 
/**
 * 提供者侧覆盖值；None = 使用模型标称值（清除已有覆盖）
 */
maxOutputTokens: number | null, 
/**
 * 提供者侧覆盖值；None = 使用模型标称值（清除已有覆盖）
 */
toolCalling: boolean | null, 
/**
 * 提供者侧覆盖值；None = 使用模型标称值（清除已有覆盖）
 */
vision: boolean | null, 
/**
 * 提供者侧覆盖值；None = 使用模型标称值（清除已有覆盖）
 */
thinking: boolean | null, 
/**
 * 提供者侧覆盖值；None = 使用模型标称值（清除已有覆盖）
 */
adaptiveThinking: boolean | null, inputPricePer1m: number | null, outputPricePer1m: number | null, cacheReadPricePer1m: number | null, enabled: boolean, priority: number, };
