// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新 Token 的请求体。
 */
export type UpdateTokenRequest = {
  name: string | null;
  allowedModels: Array<string> | null;
  requestQuota: number | null;
  tokenQuota: number | null;
  quotaPeriod: string | null;
  active: boolean | null;
};
