// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateModelRequest = { providerModelId: string, compatibility: string, displayName: string, maxInputTokens: number, maxOutputTokens: number, toolCalling: boolean, vision: boolean, thinking: boolean, adaptiveThinking: boolean, inputPricePer1m: number | null, outputPricePer1m: number | null, cacheReadPricePer1m: number | null, enabled: boolean, };
