// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { type DailyPoint } from "./DailyPoint";
import { type ModelRanking } from "./ModelRanking";

export type UsageSummaryResponse = {
  days: number;
  totalRequests: number;
  totalTokens: number;
  totalCostUsd: number;
  errorRate: number;
  avgTtftMs: number | null;
  /**
   * 按日序列（升序）
   */
  daily: Array<DailyPoint>;
  /**
   * 模型用量排行（按 total_tokens 降序）
   */
  modelRanking: Array<ModelRanking>;
};
