// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = {
  id: number;
  oidcSub: string;
  name: string;
  email: string | null;
  role: string;
  active: boolean;
  createdAt: number;
};
