// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = { id: number, oidc_sub: string, name: string, email: string | null, role: string, active: boolean, created_at: number, };
