// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageModelChatMessage } from "./LanguageModelChatMessage";
import type { LanguageModelReasoningConfig } from "./LanguageModelReasoningConfig";
import type { LanguageModelResponseFormat } from "./LanguageModelResponseFormat";
import type { LanguageModelTool } from "./LanguageModelTool";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * WS 聊天参数；消息和工具与上游适配层使用同一套协议无关类型。
 */
export type WsChatParams = {
  model: string;
  messages: Array<LanguageModelChatMessage>;
  tools?: Array<LanguageModelTool>;
  toolChoice?: JsonValue;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  stop?: Array<string>;
  responseFormat?: LanguageModelResponseFormat;
  reasoning?: LanguageModelReasoningConfig;
  seed?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
  logitBias?: { [key in string]: number };
  maxCompletionTokens?: number;
};
