// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsChatParams } from "./WsChatParams";

export type WsClientMessage =
  | { method: "chat"; id: string; params: WsChatParams }
  | { method: "listModels"; id: string }
  | { method: "cancel"; id: string; targetId: string };
