// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsErrorCode } from "./WsErrorCode";

export type WsErrorBody = { code: WsErrorCode; message: string };
