// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WsErrorCode =
  | "invalid_request"
  | "model_not_found"
  | "model_not_allowed"
  | "quota_exceeded"
  | "provider_error"
  | "request_not_found"
  | "internal_error";
