// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LMResponsePart } from "./LMResponsePart";
import type { WsChatDone } from "./WsChatDone";
import type { WsErrorBody } from "./WsErrorBody";
import type { WsResult } from "./WsResult";

export type WsServerMessage = { id: string, result: WsResult, } | { id: string, chunk: LMResponsePart, } | { id: string, done: WsChatDone, } | { id: string | null, error: WsErrorBody, };
